### ISSUE TITLE
TextInputSettingsTile Exception on opening editableText

### ISSUE THREAD

**Issue by eveetc** [GAM3RG33K/flutter_settings_screens#69]
When opening the editable TextInputWidget configured as in the example,
It throws the following exception (without any setState() statement)

```
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for TextEditingController:
setState() or markNeedsBuild() called during build.

This EditableText widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: EditableText-[LabeledGlobalKey<EditableTextState>#22f5a]
  controller: TextEditingController#f34ef(TextEditingValue(text: ┤├, selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1)))
  focusNode: FocusNode#7aa38([PRIMARY FOCUS])
  debugLabel: (englishLike subtitle1 2018).merge(blackMountainView subtitle1)
  inherit: true
  color: Color(0xdd000000)
  family: Roboto
  size: 16.0
  weight: 400
  letterSpacing: 0.1
  baseline: alphabetic
  decoration: TextDecoration.none
  textAlign: start
  autofocus: true
  keyboardType: TextInputType(name: TextInputType.text, signed: null, decimal: null)
  dependencies: [ScrollConfiguration, Directionality, _FocusMarker, _EffectiveTickerMode, MediaQuery]
  state: EditableTextState#53496(tickers: tracking 2 tickers)
The widget which was currently being built when the offending call was made was: ValueListenableBuilder<String>
  dirty
  state: _ValueListenableBuilderState<String>#a69aa
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4305:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4320:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1108:15)
#3      EditableTextState._didChangeTextEditingValue (package:flutter/src/widgets/editable_text.dart:2437:5)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:308:24)
#5      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:412:5)
#6      TextEditingController.value= (package:flutter/src/widgets/editable_text.dart:186:11)
#7      TextEditingController.text= (package:flutter/src/widgets/editable_text.dart:171:5)
```

**Comment by Anguel** [comment]
Same problem here. I am trying to use it in combination with flutter_bloc but no success so far. Maybe the problem is that this package uses its own state management that interferes. One thing that confuses me is that it combines a clickable tile with a dialog that pops up and you insert them at once into the UI.

**Comment by abhlabs** [comment]
Could this be related to upgrading to Flutter 2.10.x?  I'm getting it now too, but I'm pretty sure I wasn't when I first added this package to my project earlier this year, and I was on 2.5 (or maybe 2.8?) at that time.

**Comment by Anguel** [comment]
Not sure, it does not seem to appear in the example code of the package.
What exactly is your error @abhlabs ? Mine is:
```
Exception has occurred.
FlutterError (setState() or markNeedsBuild() called during build.
This AnimatedBuilder widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  AnimatedBuilder
The widget which was currently being built when the offending call was made was:
  ValueListenableBuilder<String>)
```

**Comment by Anguel** [comment]
In the meantime I received some helpful feedback from a flutter guru on Udemy. In summary he told me that "It seems that this package uses ValueChangeNotifier and setState as a tool for state management. So I think it can be hard to find the exact cause of error."
IMHO this can therefore interfere with other state management packages like flutter_bloc. Probably, the only way to solve the problem will be that the authors with their superior knowledge find a fix or workaround.

**Comment by abhlabs** [comment]
> What exactly is your error @abhlabs ?

The error I get is 100% identical to yours, word for word.  It comes up when I tap the OK button after entering some text in a TextInputSettingsTile.  The error does not stop the new input from being saved -- in fact a release build running on an actual device will work fine, although I don't know what side affects the error might be causing.

**Comment by Anguel** [comment]
Exactly, pressing OK with a changed text value triggers the exception. I even moved the settings to a separate screen because I had them inside a dialog previously but the same error occurs. What state management are you using?
In the meantime I really wonder why the demo example works without problems.

**Comment by Anguel** [comment]
I just forked the Github repo to my Github account to have a deeper look but it magically worked without problems. And I still have no changes committed!
You can try to include directly from Github. So instead of using "^0.3.2-null-safety" you include latest directly from Github like this in your pubspec.yaml:

```
dependencies:
  flutter:
    sdk: flutter
  flutter_settings_screens:
    git:
      url: https://github.com/GAM3RG33K/flutter_settings_screens

```
I don't know what is going on there, maybe the ^0.3.2-null-safety listed as prerelease on pub.dev is the problem? Not sure how this 0.3.2 exactly relates to the Github branches.

**Comment by abhlabs** [comment]
> I just forked the Github repo to my Github account to have a deeper look but it magically worked without problems. 

I can confirm that your suggestion worked.   And your theory that it relates to null safety is consistent with my experience -- I didn't make the connection at first, but I know I _didn't_ have this problem when I first added the package to my project, and probably just didn't notice it after I went through null-safety migration earlier this year.

**Comment by abhlabs** [comment]
> I don't know what is going on there, maybe the ^0.3.2-null-safety listed as prerelease on pub.dev is the problem? Not sure how this 0.3.2 exactly relates to the Github branches.

There two significantly different files in your git fork than what you get from pub.dev:  base_widgets.dart and settings_widgets.dart.  The differences are mostly related to moving the titleTextStyle and subtitleTextStlye from one class to the other.   I think that substantiates your assumption that the pub.dev version is the problem, considering that your fork works while the pub.dev version doesn't.

Maybe do a pull request?

In any event, thanks very much for your discovery, this will resolve the issue for me!

**Comment by Anguel** [comment]
Well, it is actually the current Github version of the author's package which works ok, but it differs from the one on pub.dev. I think the author should just update it on pub.dev. Unfortunately, this project looks like mostly abandoned to me. If I have time I will probably try to do some minor improvements in the future (e.g. I need a childrenIfDisabled property for a switch button) to add and then ask for a pull request. Unfortunately, it is still hard to use this package with my own flutter_bloc state management as there are some things that don't seem to be easy to achieve. On the other hand I am quite new to Flutter and also to Github and unfortunately I am very busy on top.
